### ISSUE TITLE
Duplicate enum type registration causes panic

### ISSUE THREAD

**Issue by ileyd** [micro/protoc-gen-micro#1]
I am not sure if this is an error of mine or with this package, but when defining `enum`'s in a .proto file, and compiling using this plugin, it seems that `enum`'s are registered twice, causing a panic.

In case it makes any difference, I am developing on Windows and running commands using PowerShell.

See:
```
PS C:\Users\redacted_user\go\src\gitlab.com\redacted_dir\redacted_service> go run .\main.go
panic: proto: duplicate enum registered: tld.redacted_domain.srv.redacted_service.TorrentState

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(0x9ffe3e, 0x28, 0xc0420797d0, 0xc042079800)
        C:/Users/redacted_user/go/src/github.com/golang/protobuf/proto/properties.go:815 +0x13c
gitlab.com/redacted_dir/redacted_service/proto/redacted_service.init.1()
        C:/Users/redacted_user/go/src/gitlab.com/redacted_dir/redacted_service/proto/redacted_service/redacted_service.pb.go:343 +0x1e1
exit status 2
```

I compiled my .proto file using:
```
PS C:\Users\redacted_user\go\src\gitlab.com\redacted_dir\redacted_service> protoc --proto_path=$GOSRC --proto_path=. --micro_out=. --go_out=. .\proto\redacted_service\redacted_service.proto
```

The relevant parts of my .proto file:
```
syntax = "proto3";

package tld.redacted_domain.srv.redacted_service;

service Torrents {
  // ...
  // gets an optionally filtered list of torrents
  rpc ListTorrents(ListTorrentsRequest) returns (ListTorrentsResponse) {}
}

message ListTorrentsRequest {
  // ...
  TorrentState state = 2;
  // ...
}

// describes a torrent entry in rtorrent
message Torrent {
  // ...
  TorrentState state = 4;
  // ...
}

// describes the state of a torrent
enum TorrentState {
  STOPPED = 0;
  STARTED = 1;
}
```

**Comment by asim** [comment]
This was indeed a bug. We should not be generating the enum registration. This is handled by protoc-gen-go. It has now been fixed.

**Comment by ileyd** [comment]
Thanks @asim !
