### ISSUE TITLE
Importing another proto file causes runtime error

### ISSUE THREAD

**Issue by andrew-jones** [micro/protoc-gen-micro#34]
I'm getting runtime errors importing proto definitions from other files.  I haven't investigated at this stage, but this is the result.

test.proto
```
syntax = "proto3";

import "bitbucket.org/andrewjones/service-test/proto/test/import.proto";

service Tests {
	rpc Test(TestRequest) returns (TestResponse) {}
}
```

import.proto
```
syntax = "proto3";

message TestRequest {}

message TestResponse {}
```

test.sh
```
#!/bin/bash

echo "Generating protobuf"
protoc \
    -I$GOPATH/src \
    -I/go/src/bitbucket.org/andrewjones/service-test/vendor \
    --plugin=protoc-gen-go=/usr/local/bin/protoc-gen-go \
    --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro \
    --go_out=$GOPATH/src \
    --micro_out=$GOPATH/src \
    $GOPATH/src/bitbucket.org/andrewjones/service-test/proto/test/test.proto
```

result
```
./test.sh
Generating protobuf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x564d93]

goroutine 1 [running]:
github.com/micro/protoc-gen-micro/generator.(*Generator).generateImports(0xc00009c000)
	/go/src/github.com/micro/protoc-gen-micro/generator/generator.go:1356 +0x493
github.com/micro/protoc-gen-micro/generator.(*Generator).generate(0xc00009c000, 0xc0000b0090)
	/go/src/github.com/micro/protoc-gen-micro/generator/generator.go:1238 +0x195
github.com/micro/protoc-gen-micro/generator.(*Generator).GenerateAllFiles(0xc00009c000)
	/go/src/github.com/micro/protoc-gen-micro/generator/generator.go:1163 +0x255
main.main()
	/go/src/github.com/micro/protoc-gen-micro/main.go:88 +0x1c7
--micro_out: protoc-gen-micro: Plugin failed with status code 2.
```

**Comment by asim** [comment]
This is due to a change introduced by @fage9958. I will revert the change and let @fage9958 PR something that doesn't break.

**Comment by asim** [comment]
I merged the fix
